//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonellerUygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personels
    {
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string PersonelSehir { get; set; }
        public Nullable<int> PersonelMaas { get; set; }
        public Nullable<bool> PersonelDurum { get; set; }
        public Nullable<int> PerYas { get; set; }
    }
}
